### PR TITLE
#193 Fix InvalidCastException

### PR DESCRIPTION
**Pull request by AlirezaMaddah**
If any of Dropbox APIs return a string with a DateTime format and we try to read it as a string using the StringDecoder, an InvalidCastException will be thrown. The proposed solution is as follows:
1. Turn off DateTime parsing by JsonTextReader: in this case, Newtonsoft will no longer treat strings with date format as DateTime.
2. Perform parsing in DateTimeDecoder using the same Culture and DateTimeKind. (The same settings compared to JsonTextReader settings).
3. Added tests to verify the behavior.

Note that the best way to resolve this issue is to use "JsonReader.ReadAsString" method for StringDecoder. But, as we call the "JsonReader.Read" method in our private Read<T> method after reading the current value, we need to review our approach.

## **Checklist**

**General Contributing**
- [x] Have you read the Code of Conduct and signed the [CLA](https://opensource.dropbox.com/cla/)?

**Is This a Code Change?**
- [ ] Non-code related change (markdown/git settings etc)
- [x] SDK Code Change
- [ ] Example/Test Code Change

**Validation**
- [x] Does this code build successfully?
- [x] Do all tests pass?
- [x] Does Stylecop pass?

### CODE REVIEW

**Comment by AlirezaMaddah** [comment]
@greg-db Could you please help me check why the CI/CD pipeline is failing? Thanks!

**Comment by greg-db** [comment]
Thanks! We'll take a look.

**Comment by connorworley** [comment]
It seems like GitHub made a breaking change to actions that is causing CI to fail for all PRs. #196 will fix this so I recommend waiting fo that to land first and rebasing against it.

**Comment by AlirezaMaddah** [comment]
Thanks, @connorworley|

**Comment by connorworley** [comment]
Hi, FYI v6.0.0 has been released!

**Comment by AlirezaMaddah** [comment]
@connorworley Could you please take the time to review?

**Review by connorworley — APPROVED** [review]
lgtm

**Pull request merged**
