### PR TITLE
Add support for generating a .Net Standard 2.0 library

### PR DESCRIPTION
**Pull request by newky2k**
Added .net standard csproj generation to the python scripts, updated the sln file to include the net standard project and updated the nuspec file to include the net standard dll

### CODE REVIEW

**Comment by greg-db** [comment]
Thanks!

**Comment by Still34** [comment]
Is this getting merged anytime soon? It's been a while and would love to see official .NETNS target.

**Comment by greg-db** [comment]
I can't make any promises as to if/when this may be merged, but I'll ask the team to look into it.

**Comment by daanl** [comment]
Please merge! :-) 👍

**Comment by greg-db** [comment]
Released in [v4.9.0](https://github.com/dropbox/dropbox-sdk-dotnet/releases/tag/v4.9.0).

**Pull request merged**
